services:
  - type: web
    name: smart-water-quality
    runtime: python
    repo: https://github.com/votre-compte/smart-water-quality
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_final:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0